# bundle exec jekyll serve --host=0.0.0.0

title: MycilaESPConnect
description: Simple & Easy Network Manager for ESP32 with WiFi, Ethernet and Captive Portal support
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  